"""create agent_memories

Revision ID: 198bd59aaddb
Revises: 0553c1b66062
Create Date: 2026-09-29 14:38:32.925247
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '198bd59aaddb'
down_revision: str | Sequence[str] | None = '0553c1b66062'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('source_session_id', sa.UUID(), nullable=True),
    sa.Column('source_event_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_event_id'], ['session_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_memories_importance_updated', 'agent_memory', ['importance', 'updated_at'], unique=False)
    op.create_index('ix_agent_memories_kind_enabled', 'agent_memory', ['kind', 'enabled'], unique=False)
    op.create_index('ix_agent_memories_source_session', 'agent_memory', ['source_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_memories_source_session', table_name='agent_memory')
    op.drop_index('ix_agent_memories_kind_enabled', table_name='agent_memory')
    op.drop_index('ix_agent_memories_importance_updated', table_name='agent_memory')
    op.drop_table('agent_memory')
    # ### end Alembic commands ###
