"""create file_object

Revision ID: d4a4d9bfb479
Revises: 0935d9c5ae18
Create Date: 2026-08-25 11:05:53.560578
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'd4a4d9bfb479'
down_revision: str | Sequence[str] | None = '0935d9c5ae18'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('original_name', sa.String(length=255), nullable=False),
            sa.Column('stored_name', sa.String(length=255), nullable=False),
            sa.Column('content_type', sa.String(length=120), nullable=False),
            sa.Column('size', sa.BigInteger(), nullable=False),
            sa.Column('storage_path', sa.String(length=500), nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
