services:
  # 负责持久化业务数据。后续会话、事件、文件记录都会写入数据库
  postgres:
    image: postgres:16-alpine
    container_name: curry-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-curry_agents}
    # 负责保存容器生命周期之外的数据。容器可以删，数据卷里的数据还在
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # 负责让容器之间通信。后续 API 连接数据库时，主机名会使用 postgres，不是 localhost
    networks:
      - curry-network
    # 负责告诉 Docker 当前服务是否真的可用。容器启动和服务可用不是同一件事
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-curry_agents}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  # 负责缓存和消息流基础能力。后续后台任务和事件推送会用到它
  redis:
    image: redis:7-alpine
    container_name: curry-redis
    restart: unless-stopped
    command: >
      redis-server
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - curry-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # api相关服务
  api:
    build:
      context: ./api
    container_name: curry-api
    restart: unless-stopped
    environment:
      API_APP_NAME: ${API_APP_NAME:-CurryAgent API}
      API_ENV: ${API_ENV:-development}
      API_VERSION: ${API_VERSION:-0.1.0}
      API_PREFIX: ${API_PREFIX:-/api}
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      CORS_ALLOW_ORIGINS: ${CORS_ALLOW_ORIGINS:-["http://localhost:3000","http://127.0.0.1:3000"]}
      CORS_ALLOW_CREDENTIALS: ${CORS_ALLOW_CREDENTIALS:-true}
      CORS_ALLOW_METHODS: ${CORS_ALLOW_METHODS:-["*"]}
      CORS_ALLOW_HEADERS: ${CORS_ALLOW_HEADERS:-["*"]}
    ports:
      - "${API_PORT:-8000}:8000"
    networks:
      - curry-network
    healthcheck:
      test: [ "CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/status').read()" ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
  redis_data:

networks:
  curry-network:
    name: curry-network
    driver: bridge
