server {
    listen 80;

    # 表示这里不绑定具体域名，本地开发访问 localhost 也能命中这个配置。
    server_name _;

    client_max_body_size 20m;

    proxy_http_version 1.1;

    # 这些配置会把原始请求信息传给后端服务。后续如果要记录访问 IP、生成完整链接、判断请求协议，就会用到这些头。
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location = /api {
        proxy_pass http://api:8000;
    }

    location /api/ {
        proxy_buffering off;
        proxy_cache     off;
        proxy_pass      http://api:8000;
    }

    location = /sandbox-api {
        proxy_pass http://sandbox:8100/api;
    }

    location /sandbox-api/ {
        proxy_buffering off;
        proxy_cache     off;
        proxy_pass      http://sandbox:8100/api/;
    }

    location / {
        proxy_pass http://ui:3000;
    }
}
